import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "@/src/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js Title",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-full bg-header">
          <nav>
            <ul className="flex space-x-2">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/sample" replace>
                  Sample
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>
        <footer className="w-full bg-footer">Footer</footer>
      </body>
    </html>
  );
}
